dist: focal
language: node_js
node_js:
  - node

before_script:
  - |
   run() {
     ID=`echo "$@" | sed -e 's/ /_/g'`
     STR=`echo "$@"`
     printf "travis_fold:start:$ID\n$STR\n"
     eval "$@"
     RESULT_EVAL=$?
     printf "travis_fold:end:$ID\n"
     return $RESULT_EVAL
   }

cache: npm

script:
  - run DEBUG="simple-git" npm test
  - run npm run verify
